# Copyright © 2019-2024 Luka Arnecic.
# See the LICENSE file at the top-level directory of this distribution.

set(FLib_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}")
set(FLib_LIBRARY_DIRS "")
set(FLib_LIBRARIES "")
file(READ "${FLib_INCLUDE_DIRS}/flib/version.hpp" FLib_VERSION_HEADER)
string(REGEX MATCH "#define FLIB_VERSION_MAJOR [0-9]+" FLib_VERSION_MAJOR_LINE "${FLib_VERSION_HEADER}")
string(REGEX MATCH "#define FLIB_VERSION_MINOR [0-9]+" FLib_VERSION_MINOR_LINE "${FLib_VERSION_HEADER}")
string(REGEX MATCH "#define FLIB_VERSION_PATCH [0-9]+" FLib_VERSION_PATCH_LINE "${FLib_VERSION_HEADER}")
string(REGEX MATCH "[0-9]+" FLib_VERSION_MAJOR "${FLib_VERSION_MAJOR_LINE}")
string(REGEX MATCH "[0-9]+" FLib_VERSION_MINOR "${FLib_VERSION_MINOR_LINE}")
string(REGEX MATCH "[0-9]+" FLib_VERSION_PATCH "${FLib_VERSION_PATCH_LINE}")
set(FLib_FIND_VERSION "${FLib_VERSION_MAJOR}.${FLib_VERSION_MINOR}.${FLib_VERSION_PATCH}")
set(FLib_FOUND TRUE)